<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCNBS3NK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCNBS3NK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCNBS3NK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCNBS3NK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCNBS3NK\App_KernelDevDebugContainer([
    'container.build_hash' => 'CNBS3NK',
    'container.build_id' => '91981a0d',
    'container.build_time' => 1658422811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCNBS3NK');
