-- --------------------------------------------------------
-- Hôte:                         127.0.0.1
-- Version du serveur:           10.3.37-MariaDB-0ubuntu0.20.04.1 - Ubuntu 20.04
-- SE du serveur:                debian-linux-gnu
-- HeidiSQL Version:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- Listage des données de la table MUSE.product : ~63 rows (environ)
INSERT INTO `product` (`id`, `supplier_id`, `category_id`, `name`, `price`, `description`, `content`, `discount`, `discount_rate`, `quantity`, `image`, `image1`, `image2`) VALUES
	(1, 1, 6, 'Ignition Cavern SE', 347, '4 cordes - Table en épicéa - Fond et éclisses en érable flammé - Manche 1 pièce en érable - Touche en jatoba - Filets de table et de fond blancs - Diapason: 760 mm (30") - Largeur au sillet: 42 mm - 22 frettes - 2 micros double bobinage Höfner', 'Conditionnement (UVC) - 1 Pièce(s) - Couleur Sunburst - Corps Erable - Manche Erable - Touche Jatoba - Frettes 22 - Diapason Short scale - Micros HH - Electronique Passif - Étui inclus Non - Housse incluse Non', 0, 0.000, 20, 'Ignition Cavern SE.jpg', 'Ignition Cavern SE-1.jpg', 'Ignition Cavern SE-2.jpg'),
	(2, 2, 6, 'BTB846-CBL', 1099, '6 cordes Série BTB Corps en frêne avec ailes en okoumé Table en peuplier veiné Manche traversant en érable/noyer Touche en palissandre Diapason: 889 mm (35") Rayon de la touche: 950 mm (37,4") Largeur au sillet: 54 mm (2,13") 24 frettes Medium en acier in', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nForme\r\nBTB\r\nCouleur\r\nBleu\r\nCorps\r\nFrêne, okoumé\r\nManche\r\nErable, noyer\r\nTouche\r\nPalissandre\r\nFrettes\r\n24\r\nDiapason\r\nExtra long scale\r\nMicros\r\nHH\r\nÉlectronique\r\nActive\r\nÉtui inclus\r\nNon\r\nHousse incluse\r\nNon', 0, 0.050, 35, 'BTB846-CBL.jpg', 'BTB846-CBL-1.jpg', 'BTB846-CBL-2.jpg'),
	(3, 3, 6, 'V3 TS 2nd Gen', 599, '5 cordes Fabriquée par Sire Corps en aulne Manche 1 pièce en érable Profil du manche en C Touche en ébène Rayon de la touche: 241 mm Diapason: 34" (Long Scale) 20 frettes Medium Small Espacement entre 2 cordes: 18 mm Largeur au sillet: 46 mm Sillet en os', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCouleur\r\nSunburst\r\nCorps\r\nAulne\r\nManche\r\nErable\r\nTouche\r\nEbène\r\nFrettes\r\n20\r\nDiapason\r\nLong scale\r\nMicros\r\nJJ\r\nÉlectronique\r\nActive, passive\r\nÉtui inclu\r\nNon\r\nHousse incluse\r\nNon', 0, 0.000, 28, 'V3 TS 2nd Gen.jpg', 'V3 TS 2nd Gen-1.jpg', 'V3 TS 2nd Gen-2.jpg'),
	(4, 4, 6, 'John Petrucci Majesty 7 SM', 7333, '7 cordes Modèle signature John Petrucci Corps en acajou Table en érable marbré Manche traversant en acajou/érable flammé Touche en érable flammé 24 frettes Medium Jumbo en acier inoxydable Diapason: 648 mm (25,5") Rayon de la touche: 17"', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCouleur\r\nSpiced Melange\r\nCorps\r\nAcajou\r\nTable d\'harmonie\r\nErable\r\nManche\r\nAcajou\r\nTouche\r\nErable\r\nFrettes\r\n24\r\nDiapason\r\n648 mm\r\nMicros\r\nHH, Piezo\r\nVibrato\r\nMusic Man\r\nHousse incluse\r\nNon\r\nÉtui inclus\r\nOui', 0, 0.000, 12, 'John Petrucci Majesty 7 SM.jpg', 'John Petrucci Majesty 7 SM-1.jpg', 'John Petrucci Majesty 7 SM-2.jpg'),
	(5, 5, 6, 'AL Bootsy Collins Spacebass', 1229, '4 cordes Signature Bootsy Collins Corps en acajou Manche vissé en érable Touche en wenge Rayon de la touche: 508 mm 24 frettes Long Scale Micros actifs MEC J/TJ Electronique active MEC 2 bandes 1 réglage de volume (Push/Pull pour EQ Bypass)', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nSignature\r\nBootsy Collins\r\nCouleur\r\nPourpre\r\nCorps\r\nAcajou\r\nTable\r\nAucune\r\nManche\r\nErable\r\nTouche\r\nWenge\r\nFrettes\r\n24\r\nDiapason\r\nLong Scale\r\nPickups\r\nJJJ\r\nElectronique\r\nActif\r\nEtui inclu\r\nNon\r\nHousse inclue\r\nOui', 0, 0.000, 7, 'AL Bootsy Collins Spacebass.jpg', 'AL Bootsy Collins Spacebass-1.jpg', 'AL Bootsy Collins Spacebass-2.jpg'),
	(6, 6, 9, '793X Galaxy Giovanni Bongo Set', 439, 'Série Galaxy Giovanni Diamètres: 7 1/4" + 8 5/8" Hauteur: 17 cm Fûts en frêne nord-américain Premium Accastillage doré Cercles Comfort Curved II 4 tirants Peaux naturelles sélectionnées à la main Accastillage doré Couleur: Naturel', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nMatériau\r\nFrêne\r\nCouleur\r\nNaturel\r\nTaille du petit bongo\r\n7,25"\r\nTaille du gros bongo\r\n8,625"', 0, 0.000, 20, '793X Galaxy Giovanni Bongo Set.jpg', '793X Galaxy Giovanni Bongo Set-1.jpg', '793X Galaxy Giovanni Bongo Set-2.jpg'),
	(7, 7, 8, 'Focus Junior Drum Set Black', 179, 'Série Focus Convient aux enfants de 4 à 7 ans Grosse caisse 16"x10" Tom 08"x05" Tom 10"x06" Stand tom 13"x11" Caisse claire en bois 12"x05" Finition: Rhodoïd Couleur: Noir Paire de baguettes incl. Coussin atténuateur d\'harmoniques pour grosse caisse incl.', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nTaille de la grosse caisse\r\n16"\r\nNombre de toms\r\n2\r\nNombre de stand toms\r\n1\r\nMatériau des fûts\r\nPeuplier\r\nFinition des fûts\r\nRhodoïd\r\nCouleur des fûts\r\nNoir\r\nPailleté\r\nNon\r\nDégradé\r\nNon\r\nBurst\r\nNon\r\nFinition de l\'accastillage\r\nChrome\r\nAvec caisse claire\r\nOui\r\nCymbales incl.\r\nOui\r\nHardware incl.\r\nOui\r\nSiège incl.\r\nOui', 0, 0.000, 6, 'Focus Junior Drum Set Black.jpg', 'Focus Junior Drum Set Black-1.jpg', 'Focus Junior Drum Set Black-2.jpg'),
	(8, 7, 9, 'MC890NT Conga Set', 298, 'Set de congas 10"+11" En bois Finition: Vernis Couleur: Naturel/ambre 2 supports simples incl. Housses Millenium', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nSupport incl.\r\nOui\r\nMatériau\r\nEucalyptus\r\nCouleur\r\nNaturel\r\nTailles\r\n10", 11"\r\nVariante\r\nMillenium', 0, 0.000, 16, 'MC890NT Conga Set.jpg', 'MC890NT Conga Set-1.jpg', 'MC890NT Conga Set-2.jpg'),
	(9, 7, 8, 'MPS-850 E-Drum Set', 666, '550 sons 30 kits prédéfinis 20 kits utilisateur 100 morceaux 2 morceaux utilisateur Enregistrement rapide Métronome EQ par kit Pitch Réverbération Compresseur 6 faders pour ajuster le volume individuel des pads, du métronome et des chansons 2 sorties Main', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nRack inclus\r\nOui\r\nSiège inclus\r\nNon\r\nPédale grosse caisse incluse\r\nOui\r\nCasque inclus\r\nNon\r\nPeaux maillées\r\nOui\r\nPads double zone\r\nOui\r\nNombre de sorties directes\r\n0', 0, 0.000, 22, 'MPS-850 E-Drum Set.jpg', 'MPS-850 E-Drum Set-1.jpg', 'MPS-850 E-Drum Set-2.jpg'),
	(10, 8, 8, 'Export EXL725SBR Indigo Night', 959, 'EXL725SBR/C219 Grosse caisse 22"x18" Tom 10"x07" Tom 12"x08" Stand tom 16"x16" Caisse claire 14"x5,5" Fûts en acajou asiatique/peuplier Accastillage chromé Peaux Remo UT Peau de résonance de la grosse caisse avec évent de décompression Coussin atténuateur', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nTaille de la grosse caisse\r\n22"\r\nNombre de toms\r\n2\r\nNombre de stand toms\r\n1\r\nMatériau des fûts\r\nAcajou, peuplier\r\nFinition des fûts\r\nVernis mat\r\nCouleur des fûts\r\nBleu\r\nPailleté\r\nNon\r\nDégradé\r\nNon\r\nBurst\r\nNon\r\nFinition de l\'accastillage\r\nChrome\r\nAvec caisse claire\r\nOui\r\nCymbales incl.\r\nOui\r\nHardware incl.\r\nOui\r\nSiège incl.\r\nNon', 0, 0.100, 15, 'Export EXL725SBR Indigo Night.jpg', 'Export EXL725SBR Indigo Night-1.jpg', 'Export EXL725SBR Indigo Night-2.jpg'),
	(11, 9, 8, 'AQ1 Stage Set Piano Black', 1469, 'Série AQ1 Grosse caisse 22"x17,5" avec attache pour support de toms Tom 10"x07" Tom 12"x08" Stand tom 16"x15" Caisse claire 14"x06" Fûts 100% bouleau Accastillage chromé Système de suspension SmartMount Support double de toms incl. Couleur: Piano Black (P', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nTaille de la grosse caisse\r\n22"\r\nNombre de toms\r\n2\r\nNombre de stand toms\r\n1\r\nMatériau des fûts\r\nBouleau\r\nFinition des fûts\r\nVernis haute brillance\r\nCouleur des fûts\r\nNoir\r\nPailleté\r\nNon\r\nDégradé\r\nNon\r\nBurst\r\nNon\r\nFinition de l\'accastillage\r\nChrome\r\nAvec caisse claire\r\nOui\r\nCymbales incl.\r\nNon\r\nHardware incl.\r\nOui\r\nSiège incl.\r\nNon', 0, 0.000, 20, 'AQ1 Stage Set Piano Black.jpg', 'AQ1 Stage Set Piano Black-1.jpg', 'AQ1 Stage Set Piano Black-2.jpg'),
	(12, 10, 9, '7" Color Sound Djembe Set', 319, 'Couleurs: Rouge, orange, jaune, vert, bleu, indigo, violet Diamètres: 7" Hauteurs: 12" Fûts en matière plastique Peaux en matière plastique Très léger Idéal pour l\'éveil musical, les jardins d\'enfants et les groupes de musique pour enfants', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nTension de la peau par corde\r\nOui\r\nDiamètre en cm\r\n18 cm\r\nHauteur en cm\r\n30 cm\r\nMatériau\r\nMatière plastique', 0, 0.000, 35, '7" Color Sound Djembe Set.jpg', '7" Color Sound Djembe Set-1.jpg', '7" Color Sound Djembe Set-2.jpg'),
	(13, 11, 11, 'Nord Electro 6 HP Bundle', 2699, 'Piano de scène/synthétiseur 73 touches Mécanique à marteaux "Nord Hammer Action Portable" Fonctions Split et Layer sur les trois sections 6 points de Split avec indication LED Bibliothèque Nord Piano de 1 GB Bibliothèque Nord Sample de 512 MB', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nNombre de touches\r\n73\r\nToucher lourd\r\nOui\r\nNombre de notes de polyphonie\r\n120\r\nNombre de sons\r\n8\r\nEffets\r\nOui\r\nHaut-parleurs\r\nNon\r\nNombre de sorties casque\r\n1\r\nSéquenceur\r\nNon\r\nMétronome\r\nNon\r\nFonction clavier maître\r\nOui\r\nPitch bend\r\nNon\r\nMolette de modulation\r\nNon\r\nNombre de zones splittables\r\n3\r\nMulti-couches\r\nOui\r\nInterface MIDI\r\n1 entrée, 1 sortie', 0, 0.000, 25, 'Nord Electro 6 HP Bundle.jpg', 'Nord Electro 6 HP Bundle-1.jpg', 'Nord Electro 6 HP Bundle-2.jpg'),
	(14, 12, 11, 'Unico 500 Konkav', 39890, '56 voix d\'orgue et 7 voix orchestrales 3 claviers de 61 touches avec échappement breveté Styles: 4 préréglés et 4 utilisateurs Amplificateur 6 x 60 Watt + 1 x 100 Watt Système d\'amplification à 7 canaux 13 haut-parleurs 3 pédales d\'expression en bois Entr', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nFinition\r\nChêne clair\r\nForme des pédales\r\n32 pédales concaves', 0, 0.000, 4, 'Unico 500 Konkav.jpg', 'Unico 500 Konkav-1.jpg', 'Unico 500 Konkav-2.jpg'),
	(15, 13, 12, 'D C6 X EN Pro Black Polished', 65990, '88 touches 3 pédales (pédale centrale pour maintien de la tonalité) Longueur: 212 cm Largeur: 154 cm Hauteur: 102 cm Poids: 433 kg Finition: Noir poli Banc et casque incl.', 'Conditionnement (UVC)\r\n1 Pièce(s)', 0, 0.000, 2, 'D C6 X EN Pro Black Polished.jpg', 'D C6 X EN Pro Black Polished-1.jpg', 'D C6 X EN Pro Black Polished-2.jpg'),
	(16, 13, 11, 'PSR-SX900', 2098, '61 touches sensibles à la vélocité Nouveau clavier FSB 1337 sons + 56 kits de batterie/SFX + 480 voix XG 525 styles Polyphonie 128 voix Parties du clavier jusqu\'à Right Part3 Boutons, joystick et contrôleur Live assignables Fonctions Chord Looper', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nNombre de touches\r\n61\r\nTouches lumineuses\r\nNon\r\nSensible à la vélocité\r\nOui\r\nAftertouch\r\nNon\r\nMédia de sauvegarde\r\nUSB to Device, USB to Host\r\nAffichage des paroles\r\nOui\r\nAffichage de la partition\r\nOui\r\nHarmonie vocale\r\nOui\r\nEnregistreur audio USB\r\nOui\r\nInterface MIDI\r\n1 x In, 1 x Out\r\nEntrée microphone\r\nOui\r\nPort USB\r\nOui', 0, 0.000, 16, 'PSR-SX900.jpg', 'PSR-SX900-1.jpg', 'PSR-SX900-2.jpg'),
	(17, 13, 12, 'U1 Q PWH', 9990, '88 touches 3 pédales Hauteur: 121 cm Largeur: 153 cm Profondeur: 61 cm Poids: 228 kg Finition: Blanc poli haute brillance Banc et lampe incl.', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nFonction Silencieux\r\nNon\r\nCouleur / finition de la surface\r\nBlanc poli\r\nHauteur\r\n1210 mm', 0, 0.000, 18, 'U1 Q PWH.jpg', 'U1 Q PWH-1.jpg', 'U1 Q PWH-2.jpg'),
	(18, 14, 3, 'GK Pro Negra', 1666, 'Pan coupé Table en épicéa européen massif Fond et éclisses en palissandre indien massif Manche en acajou Touche en ébène Diapason: 650 mm Largeur au sillet: 50 mm 19 frettes Sillets de tête et de chevalet en os Mécaniques dorées Cordoba Premium', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nPan coupé\r\nOui\r\nTable\r\nEpicéa\r\nFond et éclisses\r\nPalissandre\r\nMicro\r\nOui\r\nTouche\r\nEbène\r\nLargeur au sillet en mm\r\n50 mm\r\nDiapason\r\n650 mm\r\nCouleur\r\nNaturel\r\nEtui rigide\r\nOui\r\nHousse\r\nNon', 0, 0.000, 75, 'GK Pro Negra.jpg', 'GK Pro Negra-1.jpg', 'GK Pro Negra-2.jpg'),
	(19, 15, 3, 'Celebrity Elite CE44C-4A-G', 499, 'Electro-acoustique Pan coupé Cordes en nylon Corps Mid-Depth Bowl en Lyrachord Table en cèdre massif Barrage en X optimisé Multi-rosaces Manche en acajou Profil du manche: C arrondi Nouvel angle de tête Nouvelle transition manche/tête', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCouleur\r\nNaturel\r\nTable\r\nCèdre massif\r\nFond et éclisses\r\nLyrachord\r\nTouche\r\nOvangkol\r\nLargeur au sillet en mm\r\n48,00 mm\r\nDiapason\r\n650 mm\r\nPan coupé\r\nOui\r\nMicro\r\nOui\r\nEtui rigide ou housse\r\nNon', 0, 0.050, 95, 'Celebrity Elite CE44C-4A-G.jpg', 'Celebrity Elite CE44C-4A-G-1.jpg', 'Celebrity Elite CE44C-4A-G-2.jpg'),
	(20, 16, 3, 'RM-140-NT Hot Club Solid D', 399, 'Grande Bouche - Pan coupé Table en épicéa de Sitka massif teinté Barrage en échelle Fond et éclisses en sapele Manche en Khaya Touche en pau ferro Repères "points" en nacre blanche de 5 mm Repères "points latéraux" en nacre blanche de 2 mm', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nFormat\r\nStyle Gypsy\r\nTable d\'harmonie\r\nEpicéa massif\r\nDos et éclisses\r\nSapele\r\nPan coupé\r\nOui\r\nTouche\r\nPau Ferro\r\nLargeur au sillet en mm\r\n43,60 mm\r\nFrettes\r\n20\r\nMicro\r\nNon\r\nCouleur\r\nNaturel\r\nÉtui\r\nNon\r\nHousse incl.\r\nNon', 0, 0.000, 150, 'RM-140-NT Hot Club Solid D.jpg', 'RM-140-NT Hot Club Solid D-1.jpg', 'RM-140-NT Hot Club Solid D-2.jpg'),
	(21, 16, 3, 'RM-150-NT Hot Club Solid O', 499, 'Petite Bouche Pan coupé Table en épicéa de Sitka massif teinté Barrage en échelle Fond et éclisses en sapele Manche en Khaya Touche en pau ferro Repères "points" en nacre blanche de 5 mm Repères "points latéraux" en nacre blanche de 2 mm', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nFormat\r\nStyle Gypsy\r\nTable d\'harmonie\r\nEpicéa massif\r\nDos et éclisses\r\nSapele\r\nPan coupé\r\nOui\r\nTouche\r\nPau Ferro\r\nLargeur au sillet en mm\r\n43,60 mm\r\nFrettes\r\n20\r\nMicro\r\nNon\r\nCouleur\r\nNaturel\r\nÉtui\r\nNon\r\nHousse incl.\r\nNon', 0, 0.000, 160, 'RM-150-NT Hot Club Solid O.jpg', 'RM-150-NT Hot Club Solid O-1.jpg', 'RM-150-NT Hot Club Solid O-2.jpg'),
	(22, 13, 2, 'SLG200NW NA', 799, 'Cordes en nylon Corps en acajou Eclisses en érable/palissandre Manche en acajou Touche en ébène Chevalet en palissandre 19 frettes Diapason: 650 mm Largeur au sillet: 52 mm Espacement des cordes: 11,5 mm Micro piézo SRT', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCouleur\r\nNaturel\r\nTable\r\nAucune\r\nFond et éclisses\r\nAucun\r\nTouche\r\nEbène\r\nLargeur au sillet en mm\r\n52,00 mm\r\nDiapason\r\n650 mm\r\nPan coupé\r\nOui\r\nMicro\r\nOui\r\nEtui rigide ou housse\r\nOui', 0, 0.000, NULL, 'SLG200NW NA.jpg', 'SLG200NW NA-1.jpg', 'SLG200NW NA-2.jpg'),
	(23, 17, 2, 'Les Paul Standard 50s HCS', 2390, 'Corps en acajou Table en érable Manche en acajou Touche en palissandre Repères trapézoïdes Profil du manche: Vintage 50s Filets de corps et de touche couleur crème Sillet Graph Tech Largeur au sillet: 43 mm Diapason: 628 mm 22 frettes Medium', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCouleur\r\nCherry Sunburst\r\nCorps\r\nAcajou\r\nTable\r\nErable\r\nManche\r\nAcajou\r\nTouche\r\nPalissandre\r\nFrettes\r\n22\r\nDiapason\r\n628 mm\r\nMicros\r\nHH\r\nVibrato\r\nNon\r\nÉtui inclus\r\nOui\r\nHousse incluse\r\nNon', 0, 0.000, 55, 'Les Paul Standard 50s HCS.jpg', 'Les Paul Standard 50s HCS-1.jpg', 'Les Paul Standard 50s HCS-2.jpg'),
	(24, 18, 2, 'G100CE BK', 899, 'Synchromatic Table bombée en épicéa Corps en érable Largeur du corps: env. 406,4 mm Profondeur du corps: 69,85 mm Manche 3 pièces en érable Touche en palissandre 20 frettes Diapason: 648 mm Largeur au sillet: 43 mm 1 micro simple bobinage Gretsch', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCouleur\r\nNoir\r\nCorps\r\nErable\r\nTable\r\nEpicéa\r\nManche\r\nErable\r\nTouche\r\nPalissandre\r\nFrettes\r\n20\r\nDiapason\r\n648 mm\r\nMicros\r\nH\r\nVibrato\r\nNon\r\nEtui inclus\r\nNon\r\nHousse incluse\r\nNon', 0, 0.150, 39, 'G100CE BK.jpg', 'G100CE BK-1.jpg', 'G100CE BK-2.jpg'),
	(25, 19, 2, 'DC-Custom 612 Cherry', 548, '12 et 6 cordes Série Custom Line Corps en acajou Manches collés en acajou Profil des manches en C Touches en jatoba torréfié Repères trapézoïdes Rayon des touches: 350 mm Filets de manches et de têtes Incrustation des têtes rhombes', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCouleur\r\nRouge\r\nCorps\r\nAcajou\r\nManche\r\nAcajou\r\nTouche\r\nJatoba\r\nFrettes\r\n22\r\nDiapason\r\n628 mm\r\nMicros\r\nHH, HH\r\nVibrato\r\nNon\r\nÉtui inclus\r\nOui\r\nHousse incluse\r\nNon', 0, 0.000, 218, 'DC-Custom 612 Cherry.jpg', 'DC-Custom 612 Cherry-1.jpg', 'DC-Custom 612 Cherry-2.jpg'),
	(26, 20, 13, 'MAT24 Tenor Horn', 4777, 'Série MeisterArt 4 palettes avec transition souple Perce conique: 14 - 15,5 mm Rotules 3B 3ème palette ergonomique guidé vers le haut 4ème palette légèrement courbée dans le corps Coude conique Coulisse d\'accord inversée Diamètre du pavillon: 270 mm En la', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nNombre de pistons\r\n4\r\nMatériau du pavillon\r\nLaiton doré\r\nFinition\r\nVernis clair\r\nEtui rigide ou housse\r\nOui', 0, 0.000, 45, 'MAT24 Tenor Horn.jpg', 'MAT24 Tenor Horn-1.jpg', 'MAT24 Tenor Horn-2.jpg'),
	(27, 21, 13, '12-H Ocarina C3 Signature AC', 68, 'Modèle C3 Tonalité: Do majeur Registre: Alto Tessiture: La1 - Fa3 En céramique Système asiatique Longueur: 160 mm Poids: env. 250 g Couleur: Noir/marron Méthode d\'ocarina de 72 pages, sacoche et bandoulière incl.', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nMatériau\r\nCéramique\r\nNombre de trous\r\n12\r\nPartitions\r\nOui', 0, 0.000, 536, '12-H Ocarina C3 Signature AC.jpg', '12-H Ocarina C3 Signature AC-1.jpg', '12-H Ocarina C3 Signature AC-2.jpg'),
	(28, 22, 13, 'CL-18A A-Clarinet Boehm', 849, 'Système Boehm 18 clés 5 anneaux Levier de Mib En grenadille Repose-pouce réglable avec anneau pour sangle Mécanique argentée 2 barils Accessoires incl.: Bec Ligature Protège pouce BG Ecouvillon Thomann Deluxe Chiffon microfibre Protège bec', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nClés\r\n18\r\nNombre d´anneaux\r\n5\r\nNombre de trilles\r\n4\r\nNombre de barillets\r\n2\r\nCorps\r\nGrenadier\r\nMatériau du pavillon\r\nGrenadille\r\nTexture des clés\r\nPlaqué argent\r\nType de clés\r\nStandard\r\nBec inclus\r\nOui\r\nEtui rigide / housse incl.\r\nOui', 0, 0.000, 160, 'CL-18A A-Clarinet Boehm.jpg', 'CL-18A A-Clarinet Boehm-1.jpg', 'CL-18A A-Clarinet Boehm-2.jpg'),
	(29, 22, 13, 'Didgeridoo Teak 130cm painted', 49, 'En teck Longueur: 130 cm Sonorité similaire à un instrument en eucalyptus', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nMatériau\r\nTeck\r\nLongueur\r\n120 cm – 140 cm\r\nFinition\r\nGraphismes', 0, 0.000, 322, 'Didgeridoo Teak 130cm painted.jpg', 'Didgeridoo Teak 130cm painted-1.jpg', 'Didgeridoo Teak 130cm painted-2.jpg'),
	(30, 22, 13, 'Mc Big Bagpipes Cocus L', 198, 'Modèle large Bois de Cocus Finition polie Eléments couleur ivoire Sac synthétique 28" x 12" Accessoires et anches incl.', 'Conditionnement (UVC)\r\n1 Pièce(s)', 0, 0.050, 463, 'Mc Big Bagpipes Cocus L.jpg', 'Mc Big Bagpipes Cocus L-1.jpg', 'Mc Big Bagpipes Cocus L-2.jpg'),
	(31, 22, 13, 'TR-901S Piccolo Trumpet', 459, '4 pistons Périnet Finition: Plaqué argent 2 branches d\'embouchure: Sib et La Embouchure 7C et étui souple incl.', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nPavillon\r\n11,68 mm\r\nMatériau du pavillon\r\nLaiton\r\nType de pistons\r\nPerinet\r\nMatériau de la branche d\'embouchure\r\nLaiton\r\nFinition\r\nPlaqué argent\r\nEmbouchure incluse\r\nOui\r\nEtui rigide / housse incl.\r\nOui', 0, 0.000, 122, 'TR-901S Piccolo Trumpet.jpg', 'TR-901S Piccolo Trumpet-1.jpg', 'TR-901S Piccolo Trumpet-2.jpg'),
	(32, 13, 13, 'YBS-480 Baritone Saxophone', 6295, 'Descend jusqu\'au La grave Finition vernis doré Perce verticale Le design du bocal en S a été adopté à partir du YBS-62II Le pavillon court facilite l\'intonation des notes graves Livré avec étui et bocal', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nFinition du corps\r\nVernis doré\r\nFinition du clétage\r\nVernis doré\r\nCorps\r\nLaiton\r\nClé de La grave\r\nOui\r\nClé de Fa# aigu\r\nOui\r\nBec\r\nOui\r\nChiffon\r\nNon\r\nSangle de saxophone\r\nNon\r\nPiquet\r\nNon\r\nÉtui avec roulettes\r\nNon', 0, 0.000, 18, 'YBS-480 Baritone Saxophone.jpg', 'YBS-480 Baritone Saxophone-1.jpg', 'YBS-480 Baritone Saxophone-2.jpg'),
	(33, 13, 13, 'YSL-448 GE II Trombone', 1219, 'Perce: 13,34 mm Pavillon en laiton doré: 241,4 mm Finition: Vernis Coulisse en maillechort Etui rigide et embouchure 48 incl.', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nPavillon\r\nLaiton doré\r\nMatériau des coulisses extérieures\r\nMaillechort\r\nEtui rigide ou housse\r\nOui\r\nPerce\r\n13,34 mm\r\nFinition\r\nVernis clair', 0, 0.000, 48, 'YSL-448 GE II Trombone.jpg', 'YSL-448 GE II Trombone-1.jpg', 'YSL-448 GE II Trombone-2.jpg'),
	(34, 23, 14, 'Novita 3.0 UA Elec. Violin BK', 749, '4 cordes Design fonctionnel Dimensions de base identiques à un violon classique Finition: Vernis mat Structure du bois apparente Manche en érable massif Volute élaborée Chevilles d\'accordage fin Wittner Mentonnière Wittner Zurich', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nNombre de cordes\r\n4\r\nTouche\r\nEbène\r\nCorps\r\nBois\r\nChevilles\r\nMétal/plastique\r\nMentonnière\r\nMatière plastique\r\nManche\r\nErable\r\nHousse incluse\r\nNon\r\nÉtui inclus\r\nNon\r\nArchet inclus\r\nNon\r\nCoussin\r\nNon\r\n4 mécaniques précises incluses\r\nNon', 0, 0.000, 365, 'Novita 3.0 UA Elec. Violin BK.jpg', 'Novita 3.0 UA Elec. Violin BK-1.jpg', 'Novita 3.0 UA Elec. Violin BK-2.jpg'),
	(35, 24, 14, 'NXT4a-DB-BK Electric Bass', 1985, '4 cordes Corps en érable Manche en érable Touche en Richlite Chevalet réglable en hauteur Barre de tension (Truss Rod) réglable Sortie active Dual Mode Système de micro Polar Modes Arco et Pizzicato commutables Contrôles: Volume et tonalité Couleur: Noir', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nTaille\r\n3/4\r\nTouche\r\nEbène\r\nÉlectronique\r\nActive\r\nChevalet réglable en hauteur\r\nOui\r\nHousse incluse\r\nOui\r\nÉtui inclus\r\nNon\r\nArchet inclus\r\nNon\r\nSupport incl.\r\nOui\r\nPiquet inclus\r\nNon', 0, 0.000, 68, 'NXT4a-DB-BK Electric Bass.jpg', 'NXT4a-DB-BK Electric Bass-1.jpg', 'NXT4a-DB-BK Electric Bass-2.jpg'),
	(36, 25, 14, 'SALTIT-MSS Titan Mahogany', 2790, '38 cordes Tessiture: Do1 - Do6 Cordes en Silkgut Hauteur: 1500 mm Largeur: 780 mm Poids: 12,5 kg Couleur: Acajou Clé d\'accordage et housse de protection incl.', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nAccordage\r\nDo1 - La6\r\nDimensions\r\n1500 x 780 mm\r\nIncl. housse\r\nNon', 0, 0.000, 84, 'SALTIT-MSS Titan Mahogany.jpg', 'SALTIT-MSS Titan Mahogany-1.jpg', 'SALTIT-MSS Titan Mahogany-2.jpg'),
	(37, 26, 14, 'Vilagio Double Bass Ceruti IB', 4980, 'Forme de violon selon Giovanni Battista Ceruti Fabriquée dans l\'atelier de maître de Ioan Bucur Table en épicéa massif Fond bombé en érable magnifiquement flammé Eclisses en érable magnifiquement flammé Touche en ébène Diapason: 1045 mm', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nTaille\r\n3/4\r\nTable\r\nEpicéa\r\nDos\r\nErable massif bombé\r\nTouche\r\nEbène\r\nMécaniques\r\nMécanique simple\r\nHousse incluse\r\nNon\r\nArchet inclus\r\nNon\r\nChevalet réglable en hauteur\r\nNon', 0, 0.000, 80, 'Vilagio Double Bass Ceruti IB.jpg', 'Vilagio Double Bass Ceruti IB-1.jpg', 'Vilagio Double Bass Ceruti IB-2.jpg'),
	(38, 26, 14, 'Vilagio Gothic Hurdy Gurdy', 1490, '1 1/2 octave Chromatique Table en épicéa Fond, éclisses et structure en érable 1 corde de mélodie 2 bourdons Corde de mélodie en Sol ou Fa Fabriquée en Europe', 'Conditionnement (UVC)\r\n1 Pièce(s)', 0, 0.080, 76, 'Vilagio Gothic Hurdy Gurdy.jpg', 'Vilagio Gothic Hurdy Gurdy-1.jpg', 'Vilagio Gothic Hurdy Gurdy-2.jpg'),
	(39, 26, 14, 'Vilagio R.O. Stradivari Superieur Solo', 9666, 'Modèle d\'après Stradivari Construit par Ryszard Osowski dans le meilleur savoir-faire de l\'atelier de Haute-Franconie, en Allemagne Bois de lutherie stockés pendant de nombreuses années sélectionnés dans les meilleures régions de Bavière', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nArcher inclus\r\nNon\r\nÉtui inclus\r\nNon\r\nTouche\r\nEbène\r\nFabriqué sans bois tropicaux\r\nNon\r\nDos flammé\r\nOui\r\nCordes\r\nThomastik Rondo\r\nCordier avec vis d\'accordage fin\r\nNon\r\nAccordage fin pour corde de Mi\r\nOui', 0, 0.000, 19, 'Vilagio R.O. Stradivari Superieur Solo.jpg', 'Vilagio R.O. Stradivari Superieur Solo-1.jpg', 'Vilagio R.O. Stradivari Superieur Solo-2.jpg'),
	(40, 22, 14, 'Gothic Black Cello', 449, 'Table, fond et éclisses en tilleul laminé Manche en érable Touche en bois dur Chevilles en bois Cordier avec vis d\'accordage fin Pique réglable en hauteur Cordes Jargar Classic Medium Couleur: Noir Housse rembourrée, archet en composite et colophane incl.', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nTouche\r\nBois dur\r\nTable massive\r\nNon\r\nDos flammé\r\nNon\r\nIncl. housse\r\nOui\r\nIncl. étui/coffret\r\nNon\r\nArchet inclus\r\nOui\r\nVersion gaucher\r\nNon', 0, 0.100, 78, 'Gothic Black Cello.jpg', 'Gothic Black Cello-1.jpg', 'Gothic Black Cello-2.jpg'),
	(41, 22, 14, 'Lute Guitar Standard Walnut', 498, 'Fabriquée en Europe Diapason: 650 mm Cordes en nylon Galli LG40 Table en épicéa massif Corps en noyer Manche en acacia Chevalet en acacia traité thermiquement Touche en acacia teinté noir Tête en chêne foncé', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCouleur\r\nNaturel\r\nTable\r\nEpicéa\r\nFond et éclisses\r\nNoyer\r\nTouche\r\nAcacia\r\nLargeur au sillet en mm\r\n5,00 mm\r\nDiapason\r\n650 mm\r\nPan coupé\r\nNon\r\nMicro\r\nNon\r\nEtui rigide ou housse\r\nOui', 0, 0.050, 167, 'Lute Guitar Standard Walnut.jpg', 'Lute Guitar Standard Walnut-1.jpg', 'Lute Guitar Standard Walnut-2.jpg'),
	(42, 22, 14, 'Nataraj Sitar Student', 398, 'Style Ravi Shankar 7 cordes mélodiques 11 cordes sympathiques 20 frettes 2 accordages fins à l\'extrémité inférieure Diapason: env. 855 mm 2 accordages fins à l\'extrémité supérieure Ornements de qualité Résonateur dévissable au niveau de la tête Longueur t', 'Conditionnement (UVC)\r\n1 Pièce(s)', 0, 0.080, NULL, 'Nataraj Sitar Student.jpg', 'Nataraj Sitar Student-1.jpg', 'Nataraj Sitar Student-2.jpg'),
	(43, 13, 14, 'SVC 110 Silent Cello', 2690, 'Taille 4/4 Diapason: 695 mm Manche en érable Touche et chevilles en ébène 4 vis d\'accordage fin Cordes D\'Addario Helicore Transducteur piézo Réverbération intégrée Entrée Aux sur mini Jack 3,5 mm Sortie ligne sur Jack 6,3 mm Câble mini Jack stéréo 3,5 mm', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nHousse incluse\r\nOui\r\nÉtui inclus\r\nNon\r\nArchet inclus\r\nNon\r\n4 mécaniques précises\r\nOui\r\nSupport incl.\r\nNon\r\nPiquet inclus\r\nOui', 0, 0.000, 64, 'SVC 110 Silent Cello.jpg', 'SVC 110 Silent Cello-1.jpg', 'SVC 110 Silent Cello-2.jpg'),
	(44, 27, 15, 'DJ Learning Kit', 198, 'Contrôleur DJ Control Inpulse 200 avec interface audio USB intégrée :  Commandes par platine : molettes Jogwheel (90 mm) Touché Vinyl Feeling avec reconnaissance de pression 4 pads avec 4 modes (Hot-Cue, Roll, FX, Sampler)', 'Conditionnement (UVC)\r\n1 Pièce(s)', 0, 0.000, 182, 'DJ Learning Kit.jpg', 'DJ Learning Kit-1.jpg', 'DJ Learning Kit-2.jpg'),
	(45, 28, 15, '201-USB Play Bundle', 584, 'the t.mix 201-USB Play Fun Generation PL 15 Sub A Fun Generation Speaker Stand Pair 2 pièce Fun Generation PL 108 A 2 pièce pro snake TPA 1003 FR 2 pièce the sssnake SM10BK 2 pièce the sssnake SM6BK', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCanaux ligne\r\n2\r\nEntrée Phone\r\n2\r\nEntrée microphone\r\n1\r\nEntrée interface audio\r\n0\r\nSortie interface audio\r\n0\r\nSortie Rec\r\nRCA (Cinch)\r\nSortie Master\r\nXLR\r\nSend/Return\r\nNein\r\nRackable/kit de montage en rack 19"\r\nNon\r\nTalk-Over\r\nOui\r\nEffets\r\nNon\r\nLargeur\r\n310 mm\r\nProfondeur\r\n235 mm\r\nHauteur\r\n115 mm', 0, 0.000, 32, '201-USB Play Bundle.jpg', '201-USB Play Bundle-1.jpg', '201-USB Play Bundle-2.jpg'),
	(46, 29, 16, 'BCM 104', 999, 'Spécialement conçu pour la parole/diffusion Protection intégrée contre les claquements et les bruits de structure Récepteur à gradient de pression Directivité: Cardioïde Réponse en fréquence: 20 - 20000 Hz', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nÀ lampe\r\nNon\r\nPlusieurs directivités\r\nNon\r\nOmni-directionnel\r\nNon\r\nDirectivité cardioïde\r\nOui\r\nBi-directionnel\r\nNon\r\nCoupe-Bas\r\nNon\r\nPad\r\nNon\r\nSuspension type araignée incl.\r\nNon\r\nMicrophone USB\r\nNon', 0, 0.000, 22, 'BCM 104.jpg', 'BCM 104-1.jpg', 'BCM 104-2.jpg'),
	(47, 29, 16, 'KU100', 7999, '2x capsules intégrées au niveau des oreilles Nécessite une alimentation Phantom +48V, une alimentation externe ou via batterie intégrée Commutateur d\'alimentation sous le micro, ainsi qu\'une sortie symétrique XLR ou BNC Pad atténuateur -10 dB Filtre coupe', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nAlimentation par piles\r\nOui', 0, 0.000, 16, 'KU100.jpg', 'KU100-1.jpg', 'KU100-2.jpg'),
	(48, 30, 16, 'NT1-A Complete Vocal Recording', 177, 'Microphone large membrane Rode NT1-A Suspension élastique deluxe SM6 avec filtre anti-pop en tissu intégré Câble XLR de 6 m Sac de protection contre la poussière Données techniques NT1-A :  Microphone large membrane de 1 pouce Diagramme polaire : cardioïd', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nÀ lampe\r\nNon\r\nPlusieurs directivités\r\nNon\r\nOmni-directionnel\r\nNon\r\nDirectivité cardioïde\r\nOui\r\nBi-directionnel\r\nNon\r\nCoupe-Bas\r\nNon\r\nPad\r\nNon\r\nSuspension type araignée incl.\r\nOui\r\nMicrophone USB\r\nNon', 0, 0.000, 188, 'NT1-A Complete Vocal Recording.jpg', 'NT1-A Complete Vocal Recording-1.jpg', 'NT1-A Complete Vocal Recording-2.jpg'),
	(49, 31, 16, 'E 945', 189, 'Egalement utilisable pour la prise de son de cuivres Version sans interrupteur marche/arrêt Directivité: Supercardioïde Réponse en fréquence: 40 - 18.000 Hz Impédance: 350 Ohm Sensibilité: 2.0 mV/Pa à 1KHz', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nInterrupteur\r\nNon\r\nCaractéristique\r\nSupercardioide\r\nCouleur\r\nNoir bleu\r\nCâble\r\nNon', 0, 0.000, 88, 'E 945.jpg', 'E 945-1.jpg', 'E 945-2.jpg'),
	(50, 32, 16, 'SM58 LC', 99, 'Version sans interrupteur marche/arrêt Directivité: Cardioïde Réponse en fréquence: 50 - 15.000 Hz Sensibilité: -56 dBV/Pa (1,85 mV) Dimensions: 23 x 162 x 51 mm Poids: 298 g Pince, adaptateur de réduction de pas de vis 3/8" et trousse incl.', 'Interrupteur\r\nNon\r\nCaractéristique\r\nCardioide\r\nCouleur\r\nNoir\r\nCâble\r\nNon', 0, 0.050, 569, 'SM58 LC.jpg', 'SM58 LC-1.jpg', 'SM58 LC-2.jpg'),
	(51, 32, 16, 'SM 7 B', 377, 'Directivité: cardioïde Réponse en fréquence: 50 Hz - 20 kHz Sensibilité: -59,0 dB (1,12 mV) Filtre coupe bas Rehausseur de médiums Impédance : 150 Ohm Blindage interférence électromagnétique Pince micro fixe avec pas de vis', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nÀ lampe\r\nNon\r\nPlusieurs directivités\r\nNon\r\nOmni-directionnel\r\nNon\r\nDirectivité cardioïde\r\nOui\r\nBi-directionnel\r\nNon\r\nCoupe-Bas\r\nOui\r\nPad\r\nNon\r\nSuspension type araignée incl.\r\nNon\r\nMicrophone USB\r\nNon', 0, 0.000, 57, 'SM 7 B.jpg', 'SM 7 B-1.jpg', 'SM 7 B-2.jpg'),
	(52, 33, 17, 'F1 Complete Bundle', 4899, 'Caisson de basses Puissance: 1000 W 2x haut-parleurs de 10" avec une haute excursion de cône Design compact et léger avec poignée de chariot intégrée Montage pour haut-parleurs intégré F1 Model.812 Dimensions: 688 x 410 x 449 mm Poids: 24,9 kg', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nChassis plastique\r\nOui\r\nSystème satellite\r\nNon\r\nMixer inclus\r\nNon\r\nPieds incl.\r\nNon\r\nTweeter 1" et plus\r\nOui\r\nHP Médium du satellite\r\n1 x 12"\r\nComposition de l\'enceinte\r\n2 x 10"', 0, 0.000, 36, 'F1 Complete Bundle.jpg', 'F1 Complete Bundle-1.jpg', 'F1 Complete Bundle-2.jpg'),
	(53, 34, 17, 'Curv 500 PS Bundle', 2245, 'LD Systems Curv 500 Cable 3 2 pièce LD Systems Curv 500 Sat Bag 2 pièce LD Systems Curv 500 PC LD Systems Curv 500 PS', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nChassis plastique\r\nOui\r\nSystème satellite\r\nOui\r\nMixer inclus\r\nNon\r\nPieds incl.\r\nOui\r\nTweeter 1" et plus\r\nOui\r\nHP Médium du satellite\r\n1 x 4"\r\nComposition de l\'enceinte\r\n1 x 10"', 0, 0.200, 43, 'Curv 500 PS Bundle.jpg', 'Curv 500 PS Bundle-1.jpg', 'Curv 500 PS Bundle-2.jpg'),
	(54, 22, 17, 'Band Bundle M', 1444, 'Millenium BS-2211B MKII Set 2 pièce Behringer Eurolive VS1520 2 pièce Behringer Eurolive VS1220F Behringer Xenyx X2222USB the t.amp TSA 4-700 4 pièce the sssnake SLP21510 2 pièce the sssnake MXP1015', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nChassis plastique\r\nNon\r\nMixer amplifiée inclus\r\nNon\r\nAmpli inclus\r\nOui\r\nPieds incl.\r\nOui\r\nTweeter 1" et plus\r\nOui\r\nTaille du HP médium du satellite\r\n1 x 15"', 0, 0.000, 12, 'Band Bundle M.jpg', 'Band Bundle M-1.jpg', 'Band Bundle M-2.jpg'),
	(55, 35, 5, 'TB10', 2588, '4 cordes Jumbo Pan coupé Table bombée en épicéa de Sitka Fond bombé et éclisses en érable flammé Manche en érable Touche en ébène Diapason: 864 mm Sillet en os Largeur au sillet: 46,35 mm Préamplificateur CTP-2 Cool Tube', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCordes\r\n4\r\nVersion gaucher\r\nNon\r\nCouleur\r\nRouge\r\nTable\r\nEpicéa\r\nDos et éclisses\r\nErable\r\nManche\r\nÉrable\r\nTouche\r\nEbène\r\nMicros\r\nOui\r\nÉtui inclus\r\nOui\r\nHousse incluse\r\nNon', 0, 0.000, 38, 'TB10.jpg', 'TB10-1.jpg', 'TB10-2.jpg'),
	(56, 5, 5, 'Alien Deluxe 6 NT', 1599, '6 cordes Série RockBass Table en épicéa de Sitka AA massif Fond et éclisses en noyer Manche collé en acajou Touche en wenge Rayon de la touche: 47" Diapason: 34" (Long Scale) Largeur au sillet: 52 mm Sillet Just-A-Nut III en Tedur', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCouleur\r\nNaturel\r\nTable\r\nEpicéa, Massif\r\nFond et éclisses\r\nNoyer\r\nManche\r\nAcajou\r\nTouche\r\nWenge\r\nFrettes\r\n24\r\nDiapason\r\n864 cm\r\nLargeur du manche\r\n52 mm\r\nSystème de micro\r\nOui\r\nEtui inclus\r\nNon\r\nHousse incluse\r\nOui', 0, 0.000, 84, 'Alien Deluxe 6 NT.jpg', 'Alien Deluxe 6 NT-1.jpg', 'Alien Deluxe 6 NT-2.jpg'),
	(57, 5, 5, 'RB Star Bass 5 SCWHP', 1049, '5 cordes Table, fond et éclisses en érable Manche 4 pièces collé en érable laminé avec bandes en placage d\'ekanga Touche en wenge 21 frettes Extra High Jumbo en maillechort Diapason: 864 mm (Long Scale) Largeur au sillet: 45 mm', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCouleur\r\nBlanc\r\nCorps\r\nErable\r\nManche\r\nErable, ekanga\r\nTouche\r\nWenge\r\nFrettes\r\n21\r\nDiapason\r\nLong scale\r\nMicros\r\nSS\r\nElectronique\r\nPassive\r\nEtui inclu\r\nNon\r\nHousse incluse\r\nNon', 0, 0.000, 95, 'RB Star Bass 5 SCWHP.jpg', 'RB Star Bass 5 SCWHP-1.jpg', 'RB Star Bass 5 SCWHP-2.jpg'),
	(58, 36, 18, 'IPP1030', 4, 'Longueur: 3 m Jack 6,3 mm - Jack 6,3 mm Section de câble: 0,22 mm² / AWG 24 Diamètre extérieur: 6 mm Couleur: Noir', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nCouleur\r\nNoir\r\nLongueur\r\n3,00 m\r\nDe la connectique\r\nJack TS 6,3 mm mâle\r\nVers la connectique\r\nJack TS 6,3 mm mâle', 0, 0.000, 1254, 'IPP1030.jpg', 'IPP1030-1.jpg', 'IPP1030-2.jpg'),
	(59, 7, 18, 'GS-2001 E', 8, 'Support robuste pour guitare électrique Poids: 1,3 kg Couleur: Noir', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nMatériau\r\nMétal\r\nType\r\nSupport 1 instrument\r\nCompatible avec\r\nGuitare électrique\r\nPour guitares avec laque nitro\r\nNon', 0, 0.000, 77, 'GS-2001 E.jpg', 'GS-2001 E-1.jpg', 'GS-2001 E-2.jpg'),
	(60, 37, 18, 'Regular Slinky 2221', 6, 'Pour guitare électrique Regular Slinky Tirants: 010 - 013 - 017 - 026 - 036 - 046 Acier plaqué nickel', 'Tirant des cordes\r\n010 - 046\r\nTirant max. - Tirant des cordes de\r\n0,010" – 0,046"\r\nMatériau\r\nAcier nickelé\r\nCorde de sol filetée\r\nNon', 0, 0.020, 840, 'Regular Slinky 2221.jpg', 'Regular Slinky 2221-1.jpg', 'Regular Slinky 2221-2.jpg'),
	(61, 38, 18, 'Fast Fret', 10, 'Lubrifiant/nettoyant Pour cordes et touche de guitare et basse Sans silicone Elimine la saleté/crasse accumulée Prolonge la durée de vie de toutes les cordes Lubrifie les cordes pour un jeu rapide Réduit le bruit des doigts', 'Set\r\nOui\r\nHuile\r\nNon\r\nPolissage\r\nNon\r\nNettoyant\r\nNon\r\nNettoyant cordes\r\nOui\r\nChiffon\r\nOui\r\nCire\r\nNon', 0, 0.020, 731, 'Fast Fret.jpg', 'Fast Fret-1.jpg', 'Fast Fret-2.jpg'),
	(62, 19, 18, 'Nylon Player Pick Set Mixed', 2, 'Set de 12 médiators d\'epaisseurs différentes En nylon Contenu du set:  2 x 0,58 mm 2 x 0,71 mm 2 x 0,81 mm 2 x 0,96 mm 2 x 1,2 mm 2 x 1,5 mm', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nDureté - Epaisseur\r\nVariable\r\nQuantité\r\n12', 0, 0.000, 2684, 'Nylon Player Pick Set Mixed.jpg', 'Nylon Player Pick Set Mixed-1.jpg', 'Nylon Player Pick Set Mixed-2.jpg'),
	(63, 22, 18, 'CTG-10 Clip Tuner', 5, 'Accordeur chromatique à pince Pour guitares et basses Accordage via capteur de vibration Grand écran deux couleurs pivotant (360°) Pile CR2032 incl.', 'Conditionnement (UVC)\r\n1 Pièce(s)\r\nChromatique\r\nOui\r\nÉcran\r\nLCD\r\nMicro intégré\r\nNon\r\nMétronome intégré\r\nNon\r\nConnectique pour alimentation\r\nNon\r\nType de construction\r\nClip', 0, 0.000, 891, 'CTG-10 Clip Tuner.jpg', 'CTG-10 Clip Tuner-1.jpg', 'CTG-10 Clip Tuner-2.jpg');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
